fix: redirect errors to stderr

diff --git a/gss b/gss
--- a/gss
+++ b/gss
@@ -1,19 +1,19 @@
 #!/bin/bash
 
 if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
-  echo "Not in a git repository" >&1
+  echo "Not in a git repository" >&2
   exit 1
 fi
 
 if [ -z "$1" ]; then
-  echo "Missing branch name argument" >&1
+  echo "Missing branch name argument" >&2
   exit 1
 fi
 
 branch_name="$1"
 
 branch_exists() {
-  git rev-parse --verify $branch_name >/dev/null 2>&1
+  git rev-parse --verify "$branch_name" >/dev/null 2>&1
 }
 
 on_branch() {
@@ -39,7 +39,7 @@ has_changes() {
 }
 
 has_upstream() {
-  git rev-parse --verify $branch_name@{upstream} >/dev/null 2>&1
+  git rev-parse --verify "$branch_name@{upstream}" >/dev/null 2>&1
 }
 
 stash_push_changes() {
@@ -141,17 +141,17 @@ if ! branch_exists; then
       ;;
     *)
       stash_push_changes
-      git switch --create $branch_name --no-track origin/HEAD
+      git switch --create "$branch_name" --no-track origin/HEAD
       ;;
   esac
 else
   stash_push_changes
 
   if ! has_upstream; then
-    git switch $branch_name
+    git switch "$branch_name"
     echo "No upstream configured"
   else
-    echo $(git switch $branch_name | sed '2d' | sed -E 's/(\,.+$|\.$)//')
+    git switch "$branch_name" 2>&1 | sed '2d' | sed -E 's/(\,.+$|\.$)//'
     sync_branch
   fi
 
